config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "main#home"

  resources :photos do
    post :reorder, on: :collection
  end
  resources :albums do
    post :reorder, on: :collection
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos, -> { order(:order) }

  accepts_nested_attributes_for :photos
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    load_and_authorize_resource
    skip_authorize_resource :only => :reorder
    before_action :authenticate_user!
    before_action :set_album, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @albums = Album.all.order(:order)
    end

    def reorder
      params[:order].each do |a, v|
        Album.update(a.to_i, {:order => v.to_i})
      end
      render json: {
        status: :ok
      }
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @album_attachments = @album.photos.all
    end

    def new
     @album = Album.new
     @album_attachment = @album.photos.all
    end

    # GET /posts/1/edit
    def edit
      @album_attachment = @album.photos.all
    end

    # POST /posts
    # POST /posts.json
    def create
     @album = Album.new(album_params);
     @album.order = Album.maximum(:order).to_i + 1

      respond_to do |format|
        if @album.save
          params[:photo]['picture'].each do |a|
            @photo = @album.photos.create!(:picture => a, :album_id => @album.id, :order => Photo.where({:album_id => @album.id}).maximum(:order).to_i + 1)
          end
         format.html { redirect_to @album, notice: 'Album was successfully created.' }
        else
         format.html { render action: 'new' }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @album.update(album_params)
          params[:photo]['picture'].each do |a|
            @photo = @album.photos.create!(:picture => a, :album_id => @album.id, :order => Photo.where({:album_id => @album.id}).maximum(:order).to_i + 1)
          end
          format.html { redirect_to @album, notice: 'Album was successfully updated.' }
          format.json { render :show, status: :ok, location: @album }
        else
          format.html { render :edit }
          format.json { render json: @album.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @album.destroy
      respond_to do |format|
        format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_album
        @album = Album.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def album_params
        params.require(:album).permit(:title)
      end
end

app/views/albums/_form.html.erb
<%= form_for(@album, :html => { :multipart => true }) do |f| %>
   <div class="field form-group">
     <%= f.label :title %><br>
     <%= f.text_field :title , class: "form-control"%>
   </div>

  <%= f.fields_for :album_attachment do |p| %>
    <div class="field form-group">
      <%= p.label :picture %><br>
      <%= p.file_field :picture, :multiple => true, name: "photo[picture][]" %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.submit "Submit" , class: "btn btn-success btn-lg"%>
  </div>
<% end %>

<ul class="list-inline">
  <% @album_attachment.each do |p| %>
    <li>
      <%= cl_image_tag(p.picture, {:class => "thumbnail inline", :background=>"black", :crop=>"pad", :height => 250, :width => 250}) %>
    </li>
  <% end %>
</ul>

app/views/albums/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left">Editing Album</h3>
    <%= link_to 'Back', albums_path, {:class => 'pull-right'} %>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<!-- <%= link_to 'Show', @album %> | -->

app/views/albums/index.html.erb
<div class="stories">
  <div class="panel-body clearfix">
    <h1 class="pull-left">Stories</h1>
    <% if can? [:manage], :all %>
      <%= link_to new_album_path, { :class=>'btn btn-primary pull-right'} do%>
        <span class="glyphicon glyphicon-plus"></span> New Album
      <% end %>
    <% end %>
  </div>
  <ul class="list-unstyled albums-list">
    <% @albums.each do |album| %>
      <li data-album-id="<%= album.id %>" class="single-album <% if can? :reorder, album %>sortable<% end %>">
        <div class="panel panel-default single-album">
          <div class="panel-heading clearfix">
            <h3 class="pull-left"><span class="glyphicon glyphicon-sort"></span> <%= album.title %></h3>
            <%= link_to 'Show', album, {:class => 'pull-right btn btn-primary'} %>
          </div>
          <div class="panel-body">
            <ul class="list-inline photo-list">
              <% album.photos.each do |p| %>
                <li data-photo-id="<%= p.id %>" class="<% if can? [:manage], :all %>sortable<% end %>">
                  <%= cl_image_tag(p.picture, {:class => "thumbnail inline", :background=>"black", :crop=>"pad", :height => 250, :width => 250}) %>

                  <%= link_to p, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link btn-danger' do%>
                    <span class="glyphicon glyphicon-remove"></span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
          <% if can? [:manage], :all %>
          <div class="panel-footer actions">
            <%= link_to 'Edit', edit_album_path(album), {:class => 'btn btn-link'} %>
            <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-link btn-danger' %>
          </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left"><%= @album.title %></h3>
    <%= link_to 'Back', albums_path, {:class => 'pull-right'} %>
  </div>
  <div class="panel-body">
    <div id="album_photos_container" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% @album.photos.each_with_index do |p, i| %>
        <li data-target="#album_photos_container" data-slide-to="<%= i %>" class="<%if i == 0 %>active<% end %>"></li>
        <% end %>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <% @album.photos.each_with_index do |p, i| %>
          <div class="item <%if i == 0 %>active<% end %>">
            <%= cl_image_tag(p.picture, {:class => "thumbnail inline", :background=>"black", :crop=>"pad", :height => 500, :width => 800}) %>
          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#album_photos_container" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#album_photos_container" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>