config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "main#home"

  resources :photos do
    post :reorder, on: :collection
  end
  resources :albums do
    post :reorder, on: :collection
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, ImageUploader

  belongs_to :album

  validates :picture, presence: { message: "must be provided to upload" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :update, :destroy]


  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @photos = Photo.all
  end

  def reorder
    params[:order].each do |a, v|
      Photo.update(a.to_i, {:order => v.to_i})
    end
    render json: {
      status: :ok
    }
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @photo = Photo.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    # @photo = Photo.new(photo_params)
    # @photo.order = Photo.where({:album_id => photo_params[:album_id]}).maximum(:order) + 1 || 1
    #
    # respond_to do |format|
    #   if @photo.save
    #     format.html { redirect_to @photo, notice: 'Photo successfully added.' }
    #     format.json { render :show, status: :created, location: @photo }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @photo.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    # respond_to do |format|
    #   if @photo.update(photo_params)
    #     format.html { redirect_to @photo.post, notice: 'Photo was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @photo }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @photo.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:album_id, :picture)
    end
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
<%= image_tag @photo.picture %>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :album_id %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Album</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.album_id %></td>
        <td><%= photo.picture %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%= @photo.album_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @photo.picture %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>